"""signature_requests — sign contracts as well as quotes (ADR-016)

Hand-written (NOT autogenerated). Widens the e-signature envelope to
reference a Contract in addition to a Quote:

  * `quote_id` is relaxed to NULLable (was NOT NULL).
  * `contract_id` is added (nullable, FK → contracts ON DELETE CASCADE,
    indexed — mirrors the quote_id link).
  * A CHECK constraint enforces that exactly one of the two is set, so a
    request always signs a quote XOR a contract.

Typed FKs (not a polymorphic entity_type/id) keep CASCADE integrity for
the legal record. No RLS change — the table already ENABLE+FORCE's RLS
on `organization_id`.

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-06-03 10:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "b2c3d4e5f6a7"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_CHECK = "ck_signature_requests_one_document"


def upgrade() -> None:
    op.add_column(
        "signature_requests",
        sa.Column("contract_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "signature_requests_contract_id_fkey",
        "signature_requests",
        "contracts",
        ["contract_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_signature_requests_contract_id",
        "signature_requests",
        ["contract_id"],
    )
    # Existing rows all have quote_id set, so dropping NOT NULL and adding
    # the XOR check is safe without a data migration.
    op.alter_column("signature_requests", "quote_id", nullable=True)
    op.create_check_constraint(
        _CHECK,
        "signature_requests",
        "(quote_id IS NOT NULL) <> (contract_id IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint(_CHECK, "signature_requests", type_="check")
    # Re-tightening quote_id assumes no contract-only rows exist; in a real
    # downgrade with such rows this would need a backfill/cleanup first.
    op.alter_column("signature_requests", "quote_id", nullable=False)
    op.drop_index("ix_signature_requests_contract_id", table_name="signature_requests")
    op.drop_constraint(
        "signature_requests_contract_id_fkey", "signature_requests", type_="foreignkey"
    )
    op.drop_column("signature_requests", "contract_id")
