"""sales_goals (sales targets per rep / team / org for a period)

Hand-written (NOT autogenerated): autogen mis-handles partial indexes on
the other tenant tables and would emit phantom drops. See project memory.

Adds:
  * `sales_goals` — an org-scoped sales target. Scope is implied by which
    FK is set: `owner_id` → a rep, `team_id` → a team, both null → org-wide.
    `metric` is revenue (EUR) or deal_count; `target` is Numeric for both.
    Attainment is computed at read time, never stored. Hard-deletable.

RLS ENABLE + FORCE with the same GUC-reading policy as every other tenant
table, GRANTed to crm_app.

Revision ID: a3b4c5d6e7f8
Revises: f2a3b4c5d6e7
Create Date: 2026-06-07 18:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a3b4c5d6e7f8"
down_revision: Union[str, None] = "f2a3b4c5d6e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    op.create_table(
        "sales_goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column(
            "period",
            sa.Enum("month", "quarter", "year", name="goalperiod"),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column(
            "metric",
            sa.Enum("revenue", "deal_count", name="goalmetric"),
            nullable=False,
        ),
        sa.Column("target", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sales_goals_organization_id"), "sales_goals", ["organization_id"]
    )

    op.execute("ALTER TABLE sales_goals ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE sales_goals FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON sales_goals
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON sales_goals TO crm_app;")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON sales_goals;")
    op.execute("ALTER TABLE sales_goals NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE sales_goals DISABLE ROW LEVEL SECURITY;")
    op.drop_index(op.f("ix_sales_goals_organization_id"), table_name="sales_goals")
    op.drop_table("sales_goals")
    op.execute("DROP TYPE IF EXISTS goalmetric;")
    op.execute("DROP TYPE IF EXISTS goalperiod;")
