"""custom_field_definitions + custom_fields JSONB on entities

Hand-written (NOT autogenerated): autogen produces phantom drop_index
calls for the partial unique index below. See the project memory + the
companies/quotes migrations' rationale.

Adds:
  * `custom_field_definitions` — per-org schema extension (one row per
    user-defined field on one entity type). RLS ENABLE + FORCE with the
    same GUC-reading policy as every other tenant table. One live
    definition per (org, entity_type, key) via a partial unique index.
  * `leads.custom_fields`, `customers.custom_fields`,
    `deals.custom_fields`, `companies.custom_fields` — JSONB value bag
    (default `{}`), keyed by each definition's `key`.

Revision ID: d0e1f2a3b4c5
Revises: c9d0e1f2a3b4
Create Date: 2026-06-07 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "d0e1f2a3b4c5"
down_revision: Union[str, None] = "c9d0e1f2a3b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the other tenant tables so GUC semantics match.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"

_ENTITY_TABLES = ("leads", "customers", "deals", "companies")


def upgrade() -> None:
    op.create_table(
        "custom_field_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column(
            "field_type",
            sa.Enum(
                "text",
                "textarea",
                "number",
                "date",
                "boolean",
                "select",
                "multiselect",
                "url",
                "email",
                name="customfieldtype",
            ),
            nullable=False,
        ),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("required", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custom_field_definitions_organization_id"),
        "custom_field_definitions",
        ["organization_id"],
    )
    op.create_index(
        op.f("ix_custom_field_definitions_deleted_at"),
        "custom_field_definitions",
        ["deleted_at"],
    )
    # One live definition per (org, entity_type, key). Partial on
    # deleted_at so re-adding a deleted field's key doesn't collide.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_custom_field_def_org_entity_key
          ON custom_field_definitions (organization_id, entity_type, key)
          WHERE deleted_at IS NULL;
        """
    )
    # "List this entity type's fields in display order" — the form/detail
    # query path.
    op.execute(
        """
        CREATE INDEX idx_custom_field_def_org_entity_pos
          ON custom_field_definitions (organization_id, entity_type, position)
          WHERE deleted_at IS NULL;
        """
    )

    # RLS — symmetric policy, identical GUC expression. FORCE so crm_app
    # (NOBYPASSRLS) cannot sidestep it.
    op.execute("ALTER TABLE custom_field_definitions ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE custom_field_definitions FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON custom_field_definitions
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON custom_field_definitions TO crm_app;"
    )

    # JSONB value bag on each target entity.
    for tbl in _ENTITY_TABLES:
        op.add_column(
            tbl,
            sa.Column(
                "custom_fields",
                postgresql.JSONB(astext_type=sa.Text()),
                server_default=sa.text("'{}'::jsonb"),
                nullable=False,
            ),
        )


def downgrade() -> None:
    for tbl in _ENTITY_TABLES:
        op.drop_column(tbl, "custom_fields")

    op.execute(
        "DROP POLICY IF EXISTS tenant_isolation ON custom_field_definitions;"
    )
    op.execute(
        "ALTER TABLE custom_field_definitions NO FORCE ROW LEVEL SECURITY;"
    )
    op.execute(
        "ALTER TABLE custom_field_definitions DISABLE ROW LEVEL SECURITY;"
    )

    op.execute("DROP INDEX IF EXISTS idx_custom_field_def_org_entity_pos;")
    op.execute("DROP INDEX IF EXISTS uq_custom_field_def_org_entity_key;")
    op.drop_index(
        op.f("ix_custom_field_definitions_deleted_at"),
        table_name="custom_field_definitions",
    )
    op.drop_index(
        op.f("ix_custom_field_definitions_organization_id"),
        table_name="custom_field_definitions",
    )
    op.drop_table("custom_field_definitions")
    op.execute("DROP TYPE IF EXISTS customfieldtype;")
