"""signature_requests — e-signature envelopes on quotes (ADR-016)

Hand-written (NOT autogenerated): autogen produces phantom drop_index
calls for the partial / DESC indices below and would try to recreate
existing enums. See the project memory + the quotes migration rationale.

Tenant-scoped: ENABLE + FORCE RLS with the same `app.current_org_id`
GUC policy as every other tenant table, plus a denormalised
`organization_id` so the row is RLS-scoped directly (not via the join to
`quotes`) — the "every tenant table isolates at the row level"
invariant.

`signaturestatus` is a new enum.

Revision ID: f1a2b3c4d5e6
Revises: d9f1a2b3c4e5
Create Date: 2026-06-02 13:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f1a2b3c4d5e6"
down_revision: Union[str, None] = "d9f1a2b3c4e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the rls_policies / quotes migrations so the GUC
# semantics match across every tenant table. Missing/empty GUC → NULL →
# zero rows.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    op.create_table(
        "signature_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("quote_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False, server_default="manual"),
        sa.Column(
            "status",
            sa.Enum(
                "drafted",
                "sent",
                "viewed",
                "signed",
                "countersigned",
                "declined",
                "cancelled",
                name="signaturestatus",
            ),
            nullable=False,
            server_default="drafted",
        ),
        sa.Column("signer_name", sa.String(length=255), nullable=False),
        sa.Column("signer_email", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("sign_token", sa.String(length=64), nullable=True),
        sa.Column("document_attachment_id", sa.UUID(), nullable=True),
        sa.Column("signed_document_key", sa.String(length=500), nullable=True),
        sa.Column("signed_ip", sa.String(length=64), nullable=True),
        sa.Column("signed_user_agent", sa.String(length=400), nullable=True),
        sa.Column("decline_reason", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["document_attachment_id"], ["file_attachments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_signature_requests_organization_id"),
        "signature_requests",
        ["organization_id"],
    )
    op.create_index(
        op.f("ix_signature_requests_quote_id"), "signature_requests", ["quote_id"]
    )
    op.create_index(
        op.f("ix_signature_requests_external_id"),
        "signature_requests",
        ["external_id"],
    )
    op.create_index(
        op.f("ix_signature_requests_deleted_at"),
        "signature_requests",
        ["deleted_at"],
    )
    # The manual signing link looks an envelope up by its bearer token —
    # unique so a token maps to exactly one live request. Partial on
    # NOT NULL because the token is only minted on send (drafted rows and
    # vendor-driven envelopes have none).
    op.execute(
        """
        CREATE UNIQUE INDEX uq_signature_requests_sign_token
          ON signature_requests (sign_token)
          WHERE sign_token IS NOT NULL AND deleted_at IS NULL;
        """
    )
    # "List this org's signature requests, newest first" — same shape as
    # the quotes/attachments listing indices.
    op.execute(
        """
        CREATE INDEX idx_signature_requests_org_created
          ON signature_requests (organization_id, created_at DESC)
          WHERE deleted_at IS NULL;
        """
    )

    # RLS — identical GUC expression to the other tenant tables. FORCE so
    # the app role (crm_app, NOBYPASSRLS) cannot sidestep it.
    op.execute("ALTER TABLE signature_requests ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE signature_requests FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON signature_requests
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON signature_requests TO crm_app;"
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON signature_requests;")
    op.execute("ALTER TABLE signature_requests NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE signature_requests DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP INDEX IF EXISTS idx_signature_requests_org_created;")
    op.execute("DROP INDEX IF EXISTS uq_signature_requests_sign_token;")
    op.drop_index(
        op.f("ix_signature_requests_deleted_at"), table_name="signature_requests"
    )
    op.drop_index(
        op.f("ix_signature_requests_external_id"), table_name="signature_requests"
    )
    op.drop_index(
        op.f("ix_signature_requests_quote_id"), table_name="signature_requests"
    )
    op.drop_index(
        op.f("ix_signature_requests_organization_id"),
        table_name="signature_requests",
    )
    op.drop_table("signature_requests")

    sa.Enum(name="signaturestatus").drop(op.get_bind(), checkfirst=True)
