"""file_attachments RLS — close the TD-42 cross-tenant gap

`file_attachments` carries `organization_id` but was the only tenant
table without a Row-Level Security policy: isolation rested entirely on
the API always filtering by org. A single missing `WHERE organization_id`
(or any future raw query) would leak files across tenants. This migration
brings it in line with leads/customers/deals/tasks/quotes — ENABLE +
FORCE RLS with the byte-identical `app.current_org_id` GUC policy.

Every code path that touches `file_attachments` already sets the GUC:
  * the API (`api/attachments.py`) via the `get_current_org_id` dep;
  * the PDF worker jobs (`generate_deal_pdf`/`generate_quote_pdf`) via
    `set_current_org_id`, which the transaction-scoped begin-event
    re-applies on the post-render write transaction (`pdf/store.py`).
So FORCE RLS does not break any reader/writer.

Hand-written (NOT autogenerated): autogen has no notion of RLS and would
emit nothing here, and it keeps trying to drop the partial
`idx_file_attachments_entity_created` index (see project memory).

Revision ID: c8e4d3f9a1b2
Revises: b7f3a2c1d4e8
Create Date: 2026-06-02 11:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op


revision: str = "c8e4d3f9a1b2"
down_revision: Union[str, None] = "b7f3a2c1d4e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the rls_policies + quotes migrations so the GUC
# semantics match across every tenant table. Missing/empty GUC → NULL
# → zero rows; a cross-org INSERT with the wrong/no GUC fails WITH CHECK.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    op.execute("ALTER TABLE file_attachments ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE file_attachments FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON file_attachments
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON file_attachments;")
    op.execute("ALTER TABLE file_attachments NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE file_attachments DISABLE ROW LEVEL SECURITY;")
