"""companies (B2B accounts) + company_id FKs on leads/customers/deals

Hand-written (NOT autogenerated): autogen produces phantom drop_index
calls for the partial indices below. See the project memory + the
quotes/document_templates migrations' rationale.

Adds:
  * `companies` — org-scoped account entity, RLS ENABLE + FORCE with the
    same GUC-reading policy as every other tenant table. One live account
    per (org, lower(name)) via a partial unique index.
  * `leads.company_id`, `customers.company_id`, `deals.company_id` —
    nullable FK (SET NULL) so a contact/deal can roll up under an account
    without losing it when the account is deleted.

Revision ID: c9d0e1f2a3b4
Revises: b8c9d0e1f2a3
Create Date: 2026-06-07 10:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c9d0e1f2a3b4"
down_revision: Union[str, None] = "b8c9d0e1f2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the other tenant tables so GUC semantics match.
# Missing/empty GUC → NULL → zero rows.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_companies_organization_id"), "companies", ["organization_id"]
    )
    op.create_index(op.f("ix_companies_deleted_at"), "companies", ["deleted_at"])
    # One live account per (org, case-insensitive name). Partial on
    # deleted_at so a re-create after soft-delete doesn't collide.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_companies_org_name
          ON companies (organization_id, lower(name))
          WHERE deleted_at IS NULL;
        """
    )
    # "List this org's accounts, newest first" — same shape as the other
    # listing indices.
    op.execute(
        """
        CREATE INDEX idx_companies_org_created
          ON companies (organization_id, created_at DESC)
          WHERE deleted_at IS NULL;
        """
    )

    # RLS — symmetric policy, identical GUC expression. FORCE so the
    # owner role (crm_app runs NOBYPASSRLS) cannot sidestep it.
    op.execute("ALTER TABLE companies ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE companies FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON companies
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON companies TO crm_app;")

    # company_id FK on the three contact/deal tables.
    for tbl in ("leads", "customers", "deals"):
        op.add_column(tbl, sa.Column("company_id", sa.UUID(), nullable=True))
        op.create_foreign_key(
            f"fk_{tbl}_company_id",
            tbl,
            "companies",
            ["company_id"],
            ["id"],
            ondelete="SET NULL",
        )
        op.create_index(f"ix_{tbl}_company_id", tbl, ["company_id"])


def downgrade() -> None:
    for tbl in ("leads", "customers", "deals"):
        op.drop_index(f"ix_{tbl}_company_id", table_name=tbl)
        op.drop_constraint(f"fk_{tbl}_company_id", tbl, type_="foreignkey")
        op.drop_column(tbl, "company_id")

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON companies;")
    op.execute("ALTER TABLE companies NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE companies DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP INDEX IF EXISTS idx_companies_org_created;")
    op.execute("DROP INDEX IF EXISTS uq_companies_org_name;")
    op.drop_index(op.f("ix_companies_deleted_at"), table_name="companies")
    op.drop_index(op.f("ix_companies_organization_id"), table_name="companies")
    op.drop_table("companies")
