"""fx_rates reference table (EUR-based live FX, ECB feed)

Replaces the hardcoded ``FX_TO_EUR`` dict in ``app/api/dashboard.py`` with
a real, refreshable rate layer. Global reference data — NOT tenant-scoped,
so no RLS and no ``organization_id`` (same posture as ``outbox_events`` /
``webhook_deliveries``). The ``refresh_fx_rates`` worker cron UPSERTs one
row per quote currency from frankfurter.app (ECB data) and stamps
``as_of`` so the dashboard can show an honest "rates as of <date>".

Hand-written (NOT autogenerated): autogen emits phantom drop_index calls
for partial/DESC indexes and would wreck unrelated tables. Re-chained onto
b1f7c3a9d5e2 (RLS-gap fix, #125) after it merged off the same parent — keeps
a single linear head instead of two.

Revision ID: c4d5e6f7a8b9
Revises: b1f7c3a9d5e2
Create Date: 2026-06-14 20:00:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "c4d5e6f7a8b9"
down_revision = "b1f7c3a9d5e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "fx_rates",
        sa.Column("base", sa.String(length=3), nullable=False),
        sa.Column("quote", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(18, 8), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("base", "quote"),
    )
    # No RLS: global reference data. crm_app gets CRUD automatically via the
    # ALTER DEFAULT PRIVILEGES FOR ROLE crm set in f5fde59e0dc8 (this table
    # is created by the crm owner role through Alembic).


def downgrade() -> None:
    op.drop_table("fx_rates")
