"""contracts — versioned contracts/agreements (ADR-016)

Hand-written (NOT autogenerated): autogen produces phantom drop_index
calls for the partial / DESC indices below and would also try to
recreate the existing `currency` enum. See the project memory + the
quotes migration's rationale.

Tenant-scoped, RLS ENABLE + FORCE with the same GUC-reading policy as
every other tenant table (`app.current_org_id`). Unlike quotes there is
no child line-items table — a contract stores a single agreed `value`
and links back to its source quote for the itemisation.

Money columns are `Numeric` from the start (post TD-30 / ADR-015 — the
quotes table was created as Float and later migrated; this one skips
that detour). `contractstatus` is a new enum; `currency` already exists
(created with the deals table) so it is referenced with create_type=False.

Revision ID: a1b2c3d4e5f6
Revises: f1a2b3c4d5e6
Create Date: 2026-06-03 09:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the rls_policies migration so the GUC semantics
# match across every tenant table. Missing/empty GUC → NULL → zero rows.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"

# The existing currency enum (created with `deals`) — reference, do not
# recreate.
_currency = postgresql.ENUM(name="currency", create_type=False)


def upgrade() -> None:
    op.create_table(
        "contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("quote_id", sa.UUID(), nullable=True),
        sa.Column("deal_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "sent",
                "signed",
                "active",
                "terminated",
                "expired",
                name="contractstatus",
            ),
            nullable=False,
            server_default="draft",
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("currency", _currency, nullable=False, server_default="EUR"),
        sa.Column("value", sa.Numeric(precision=12, scale=2), nullable=False, server_default="0"),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("renewal_term_months", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["superseded_by"], ["contracts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contracts_organization_id"), "contracts", ["organization_id"])
    op.create_index(op.f("ix_contracts_quote_id"), "contracts", ["quote_id"])
    op.create_index(op.f("ix_contracts_deal_id"), "contracts", ["deal_id"])
    op.create_index(op.f("ix_contracts_customer_id"), "contracts", ["customer_id"])
    op.create_index(op.f("ix_contracts_deleted_at"), "contracts", ["deleted_at"])
    # One live revision per (org, number, version). Partial on deleted_at
    # so a hard re-create after soft-delete doesn't collide.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_contracts_org_number_version
          ON contracts (organization_id, number, version)
          WHERE deleted_at IS NULL;
        """
    )
    # "List this org's contracts, newest first" — same shape as the
    # quotes/attachments/activities listing indices.
    op.execute(
        """
        CREATE INDEX idx_contracts_org_created
          ON contracts (organization_id, created_at DESC)
          WHERE deleted_at IS NULL;
        """
    )

    # RLS — symmetric policy, identical GUC expression to the other
    # tenant tables. FORCE so the owner role (which the app runs as
    # under crm_app, NOBYPASSRLS) cannot sidestep it.
    op.execute("ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE contracts FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON contracts
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON contracts TO crm_app;")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON contracts;")
    op.execute("ALTER TABLE contracts NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE contracts DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP INDEX IF EXISTS idx_contracts_org_created;")
    op.execute("DROP INDEX IF EXISTS uq_contracts_org_number_version;")
    op.drop_index(op.f("ix_contracts_deleted_at"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_customer_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_deal_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_quote_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_organization_id"), table_name="contracts")
    op.drop_table("contracts")

    sa.Enum(name="contractstatus").drop(op.get_bind(), checkfirst=True)
