"""whatsapp_accounts + conversations + messages (omnichannel inbox, phase 1)

Hand-written (NOT autogenerated): autogen mis-handles the partial / DESC
indexes on the existing tenant tables and would emit phantom drops. See
project memory.

Adds:
  * `whatsapp_accounts` — a tenant's connected WhatsApp Cloud number.
    **Deliberately NOT RLS'd**: it is a routing ROOT (like `organizations`).
    Inbound Meta webhooks are unauthenticated and identify the tenant only by
    the `phone_number_id` in the payload, so the org must be resolved BEFORE
    any tenant GUC exists — a lookup that can't sit behind RLS when the runtime
    role is NOBYPASSRLS. `phone_number_id` is globally UNIQUE (one number ↔ one
    org); the `access_token` is encrypted at rest by the app, so a non-RLS
    table leaks nothing a dump wouldn't. GRANTed to crm_app.
  * `conversations` — an inbox thread with one external contact on one channel.
    Org-scoped tenant table: RLS ENABLE + FORCE + standard GUC policy.
  * `messages` — one inbound/outbound message in a conversation. Org-scoped
    tenant table: RLS ENABLE + FORCE + standard GUC policy.

Revision ID: c5d6e7f8a9b0
Revises: 0862af48f9ca
Create Date: 2026-06-08 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c5d6e7f8a9b0"
down_revision: Union[str, None] = "0862af48f9ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"

_ACCOUNT_STATUS = sa.Enum("active", "disabled", name="whatsappaccountstatus")
_CHANNEL = sa.Enum("whatsapp", "instagram", "messenger", name="conversationchannel")
_CONV_STATUS = sa.Enum("open", "closed", name="conversationstatus")
_DIRECTION = sa.Enum("inbound", "outbound", name="messagedirection")
_MSG_TYPE = sa.Enum(
    "text",
    "image",
    "document",
    "audio",
    "video",
    "sticker",
    "location",
    "contacts",
    "unsupported",
    name="messagetype",
)
_MSG_STATUS = sa.Enum(
    "received", "pending", "sent", "delivered", "read", "failed", name="messagestatus"
)


def upgrade() -> None:
    # ---- whatsapp_accounts (routing root, NOT RLS'd) ----
    op.create_table(
        "whatsapp_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("phone_number_id", sa.String(length=64), nullable=False),
        sa.Column("waba_id", sa.String(length=64), nullable=True),
        sa.Column("display_phone_number", sa.String(length=32), nullable=True),
        sa.Column("verified_name", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column(
            "status",
            _ACCOUNT_STATUS,
            nullable=False,
            server_default="active",
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number_id", name="uq_whatsapp_accounts_phone_number_id"),
    )
    op.create_index(
        op.f("ix_whatsapp_accounts_organization_id"), "whatsapp_accounts", ["organization_id"]
    )
    op.create_index(
        op.f("ix_whatsapp_accounts_phone_number_id"), "whatsapp_accounts", ["phone_number_id"]
    )

    # ---- conversations (tenant table) ----
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("channel", _CHANNEL, nullable=False, server_default="whatsapp"),
        sa.Column("contact_wa_id", sa.String(length=32), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("status", _CONV_STATUS, nullable=False, server_default="open"),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_preview", sa.String(length=255), nullable=True),
        sa.Column("unread_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["account_id"], ["whatsapp_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "account_id",
            "contact_wa_id",
            name="uq_conversations_org_account_contact",
        ),
    )
    op.create_index(
        op.f("ix_conversations_organization_id"), "conversations", ["organization_id"]
    )
    op.create_index(op.f("ix_conversations_account_id"), "conversations", ["account_id"])
    op.create_index(op.f("ix_conversations_contact_wa_id"), "conversations", ["contact_wa_id"])
    op.create_index(
        op.f("ix_conversations_last_message_at"), "conversations", ["last_message_at"]
    )

    # ---- messages (tenant table) ----
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("wa_message_id", sa.String(length=128), nullable=True),
        sa.Column("direction", _DIRECTION, nullable=False),
        sa.Column("type", _MSG_TYPE, nullable=False, server_default="text"),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("media_id", sa.String(length=128), nullable=True),
        sa.Column("media_url", sa.String(length=1024), nullable=True),
        sa.Column("status", _MSG_STATUS, nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sender_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wa_message_id", name="uq_messages_wa_message_id"),
    )
    op.create_index(op.f("ix_messages_organization_id"), "messages", ["organization_id"])
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"])
    op.create_index(op.f("ix_messages_wa_message_id"), "messages", ["wa_message_id"])
    op.create_index(op.f("ix_messages_timestamp"), "messages", ["timestamp"])

    # whatsapp_accounts is the NON-RLS routing root (see module docstring) —
    # just grant table privileges; no policy.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON whatsapp_accounts TO crm_app;")

    # conversations + messages are tenant tables: RLS ENABLE + FORCE + policy.
    for table in ("conversations", "messages"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              FOR ALL
              USING (organization_id = {GUC_EXPR})
              WITH CHECK (organization_id = {GUC_EXPR});
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO crm_app;")


def downgrade() -> None:
    for table in ("messages", "conversations"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f("ix_messages_timestamp"), table_name="messages")
    op.drop_index(op.f("ix_messages_wa_message_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_organization_id"), table_name="messages")
    op.drop_table("messages")

    op.drop_index(op.f("ix_conversations_last_message_at"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_contact_wa_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_account_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_organization_id"), table_name="conversations")
    op.drop_table("conversations")

    op.drop_index(op.f("ix_whatsapp_accounts_phone_number_id"), table_name="whatsapp_accounts")
    op.drop_index(op.f("ix_whatsapp_accounts_organization_id"), table_name="whatsapp_accounts")
    op.drop_table("whatsapp_accounts")

    op.execute("DROP TYPE IF EXISTS messagestatus;")
    op.execute("DROP TYPE IF EXISTS messagetype;")
    op.execute("DROP TYPE IF EXISTS messagedirection;")
    op.execute("DROP TYPE IF EXISTS conversationstatus;")
    op.execute("DROP TYPE IF EXISTS conversationchannel;")
    op.execute("DROP TYPE IF EXISTS whatsappaccountstatus;")
