"""quotes + quote_line_items — versioned quotes/proposals (ADR-016)

Hand-written (NOT autogenerated): autogen produces phantom drop_index
calls for the partial / DESC indices below and would also try to
recreate the existing `currency` enum. See the project memory + the
`drop_user_billing_columns` rationale.

Both tables are tenant-scoped and get RLS ENABLE + FORCE with the same
GUC-reading policy as leads/customers/deals/tasks (`app.current_org_id`).
`quote_line_items` carries its own `organization_id` (denormalised from
the parent quote) specifically so it can be RLS-scoped at the row level
rather than relying on the join — keeps the "every tenant table enforces
isolation" invariant intact (avoids a TD-42-style gap).

`quotestatus` is a new enum; `currency` already exists (created with the
deals table) so it is referenced with create_type=False.

Revision ID: b7f3a2c1d4e8
Revises: 4d3d59906702
Create Date: 2026-06-02 09:30:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "b7f3a2c1d4e8"
down_revision: Union[str, None] = "4d3d59906702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the rls_policies migration so the GUC semantics
# match across every tenant table. Missing/empty GUC → NULL → zero rows.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"

# The existing currency enum (created with `deals`) — reference, do not
# recreate.
_currency = postgresql.ENUM(name="currency", create_type=False)


def upgrade() -> None:
    op.create_table(
        "quotes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("deal_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "sent", "accepted", "declined", "expired", name="quotestatus"
            ),
            nullable=False,
            server_default="draft",
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("currency", _currency, nullable=False, server_default="EUR"),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Float(), nullable=False, server_default="0"),
        sa.Column("tax_rate", sa.Float(), nullable=False, server_default="0"),
        sa.Column("tax_amount", sa.Float(), nullable=False, server_default="0"),
        sa.Column("total", sa.Float(), nullable=False, server_default="0"),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["superseded_by"], ["quotes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quotes_organization_id"), "quotes", ["organization_id"])
    op.create_index(op.f("ix_quotes_deal_id"), "quotes", ["deal_id"])
    op.create_index(op.f("ix_quotes_customer_id"), "quotes", ["customer_id"])
    op.create_index(op.f("ix_quotes_deleted_at"), "quotes", ["deleted_at"])
    # One live revision per (org, number, version). Partial on
    # deleted_at so a hard re-create after soft-delete doesn't collide.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_quotes_org_number_version
          ON quotes (organization_id, number, version)
          WHERE deleted_at IS NULL;
        """
    )
    # "List this org's quotes, newest first" — same shape as the
    # attachments/activities listing indices.
    op.execute(
        """
        CREATE INDEX idx_quotes_org_created
          ON quotes (organization_id, created_at DESC)
          WHERE deleted_at IS NULL;
        """
    )

    op.create_table(
        "quote_line_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("quote_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False, server_default="1"),
        sa.Column("unit_price", sa.Float(), nullable=False, server_default="0"),
        sa.Column("line_total", sa.Float(), nullable=False, server_default="0"),
        sa.Column("sort_index", sa.Integer(), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quote_line_items_organization_id"),
        "quote_line_items",
        ["organization_id"],
    )
    op.create_index(
        op.f("ix_quote_line_items_quote_id"), "quote_line_items", ["quote_id"]
    )

    # RLS — symmetric policy, identical GUC expression to the other
    # tenant tables. FORCE so the owner role (which the app runs as
    # under crm_app, NOBYPASSRLS) cannot sidestep it.
    for tbl in ("quotes", "quote_line_items"):
        op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {tbl} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {tbl}
              FOR ALL
              USING (organization_id = {GUC_EXPR})
              WITH CHECK (organization_id = {GUC_EXPR});
            """
        )
        op.execute(
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON {tbl} TO crm_app;"
        )


def downgrade() -> None:
    for tbl in ("quote_line_items", "quotes"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {tbl};")
        op.execute(f"ALTER TABLE {tbl} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {tbl} DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f("ix_quote_line_items_quote_id"), table_name="quote_line_items")
    op.drop_index(
        op.f("ix_quote_line_items_organization_id"), table_name="quote_line_items"
    )
    op.drop_table("quote_line_items")

    op.execute("DROP INDEX IF EXISTS idx_quotes_org_created;")
    op.execute("DROP INDEX IF EXISTS uq_quotes_org_number_version;")
    op.drop_index(op.f("ix_quotes_deleted_at"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_customer_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_deal_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_organization_id"), table_name="quotes")
    op.drop_table("quotes")

    sa.Enum(name="quotestatus").drop(op.get_bind(), checkfirst=True)
