"""import_jobs — bulk CSV/XLSX import tracking (ADR-016 imports slice)

Hand-written (NOT autogenerated): autogen would emit phantom drop_index
calls for the partial index below and is unaware of the RLS policy /
grants. See the project memory + the document_templates migration.

Adds:
  * `import_jobs` — org-scoped, RLS ENABLE + FORCE with the same
    GUC-reading policy as every other tenant table. Tracks one bulk
    import run: source file (in S3), mode, status, outcome counters and
    a JSONB per-row `error_report`. NOT soft-deletable (operational
    record, not a trashable CRM entity).
  * Enums `importentitytype`, `importmode`, `importstatus`.

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-06-03 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "d4e5f6a7b8c9"
down_revision: Union[str, None] = "c3d4e5f6a7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the other tenant tables so GUC semantics match.
# Missing/empty GUC → NULL → zero rows.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum("lead", "customer", name="importentitytype"),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum("create", "upsert", name="importmode"),
            nullable=False,
            server_default="create",
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "completed", "failed", name="importstatus"),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("updated_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("skipped_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_jobs_organization_id"), "import_jobs", ["organization_id"])
    # "List this org's imports, newest first" + the concurrency/daily-cap
    # guards both scan by (org, status/created_at) — one composite covers
    # the list and the guard reads.
    op.execute(
        """
        CREATE INDEX idx_import_jobs_org_created
          ON import_jobs (organization_id, created_at DESC);
        """
    )

    # RLS — symmetric policy, identical GUC expression. FORCE so the
    # owner role (crm_app runs NOBYPASSRLS) cannot sidestep it.
    op.execute("ALTER TABLE import_jobs ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE import_jobs FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON import_jobs
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON import_jobs TO crm_app;")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON import_jobs;")
    op.execute("ALTER TABLE import_jobs NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE import_jobs DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP INDEX IF EXISTS idx_import_jobs_org_created;")
    op.drop_index(op.f("ix_import_jobs_organization_id"), table_name="import_jobs")
    op.drop_table("import_jobs")

    sa.Enum(name="importstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="importmode").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="importentitytype").drop(op.get_bind(), checkfirst=True)
