"""llm_usage — per-org LLM token usage (RLS tenant table)

Cost/observability for the AI features: one row per blocking LLM completion,
attributed to an org (+ user when from a request). Tenant-scoped with the
same ENABLE+FORCE+`tenant_isolation` RLS policy as every other org table
(mirrors b1f7c3a9d5e2). The request/worker `app.current_org_id` GUC scopes
reads and writes.

Hand-written (NOT autogenerated). Single head at authoring time:
c4d5e6f7a8b9.

Revision ID: e7c8d9a0b1f2
Revises: c4d5e6f7a8b9
Create Date: 2026-06-15 10:00:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "e7c8d9a0b1f2"
down_revision = "c4d5e6f7a8b9"
branch_labels = None
depends_on = None

GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "organization_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("use_case", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False, server_default=""),
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.create_index("idx_llm_usage_org", "llm_usage", ["organization_id"])
    op.create_index("idx_llm_usage_use_case", "llm_usage", ["use_case"])
    op.create_index("idx_llm_usage_created", "llm_usage", ["created_at"])

    # Tenant isolation (defense-in-depth) — same policy shape as b1f7c3a9d5e2.
    op.execute("ALTER TABLE llm_usage ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE llm_usage FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON llm_usage
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON llm_usage;")
    op.execute("ALTER TABLE llm_usage NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE llm_usage DISABLE ROW LEVEL SECURITY;")
    op.drop_index("idx_llm_usage_created", table_name="llm_usage")
    op.drop_index("idx_llm_usage_use_case", table_name="llm_usage")
    op.drop_index("idx_llm_usage_org", table_name="llm_usage")
    op.drop_table("llm_usage")
