"""api_keys — Public-API bearer credentials (ADR-016 public-API slice)

Hand-written (NOT autogenerated): autogen is unaware of the RLS policy /
grants and would emit phantom index drops. See the project memory + the
import_jobs migration.

Adds:
  * `api_keys` — org-scoped, RLS ENABLE + FORCE with the same
    GUC-reading policy as every other tenant table. One server-to-server
    credential: sha256-at-rest `hashed_key` (unique), non-secret
    `display_prefix`, JSON `scopes`, `last_used_at`, optional
    `expires_at`, soft `revoked_at`. NOT soft-deletable (revoke is the
    lifecycle end-state). `scopes` is JSON text (no PG enum) so
    per-resource scopes can be added later without a migration.

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-06-03 13:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e5f6a7b8c9d0"
down_revision: Union[str, None] = "d4e5f6a7b8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the other tenant tables so GUC semantics match.
# Missing/empty GUC → NULL → zero rows.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    # `scopes` is JSON-encoded text (not a PG enum/array) so per-resource
    # scopes can be added later without a migration; the enum below only
    # types the catalog the app validates against in Python.
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("hashed_key", sa.String(length=64), nullable=False),
        sa.Column("display_prefix", sa.String(length=40), nullable=False),
        sa.Column("scopes", sa.Text(), nullable=False, server_default='["read"]'),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_organization_id"), "api_keys", ["organization_id"])
    # The bearer hot path looks a key up by its sha256 hash — make it a
    # unique index so the lookup is an index seek AND no two keys can
    # collide on the same hash.
    op.create_index("uq_api_keys_hashed_key", "api_keys", ["hashed_key"], unique=True)
    # "List this org's keys, newest first" — the management UI's only read.
    op.execute(
        """
        CREATE INDEX idx_api_keys_org_created
          ON api_keys (organization_id, created_at DESC);
        """
    )

    # RLS — symmetric policy, identical GUC expression. FORCE so the
    # owner role (crm_app runs NOBYPASSRLS) cannot sidestep it.
    op.execute("ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE api_keys FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON api_keys
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON api_keys TO crm_app;")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON api_keys;")
    op.execute("ALTER TABLE api_keys NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE api_keys DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP INDEX IF EXISTS idx_api_keys_org_created;")
    op.drop_index("uq_api_keys_hashed_key", table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_organization_id"), table_name="api_keys")
    op.drop_table("api_keys")
