"""document_templates — merge-field templates + contract provenance (ADR-016)

Hand-written (NOT autogenerated): autogen produces phantom drop_index
calls for the partial unique index below. See the project memory + the
contracts/quotes migrations' rationale.

Adds:
  * `document_templates` — org-scoped, RLS ENABLE + FORCE with the same
    GUC-reading policy as every other tenant table. `doc_type` is a new
    enum (only `contract` today). One live template per (org, lower(name))
    via a partial unique index.
  * `contracts.applied_template_id` — nullable FK (SET NULL) recording
    which template seeded the (frozen) contract body. Provenance only.

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2026-06-03 11:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c3d4e5f6a7b8"
down_revision: Union[str, None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the other tenant tables so GUC semantics match.
# Missing/empty GUC → NULL → zero rows.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    op.create_table(
        "document_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum("contract", name="documenttype"),
            nullable=False,
            server_default="contract",
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False, server_default=""),
        sa.Column("is_default", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_templates_organization_id"), "document_templates", ["organization_id"]
    )
    op.create_index(op.f("ix_document_templates_deleted_at"), "document_templates", ["deleted_at"])
    # One live template per (org, case-insensitive name). Partial on
    # deleted_at so a re-create after soft-delete doesn't collide.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_document_templates_org_name
          ON document_templates (organization_id, lower(name))
          WHERE deleted_at IS NULL;
        """
    )
    # "List this org's templates, newest first" — same shape as the
    # other listing indices.
    op.execute(
        """
        CREATE INDEX idx_document_templates_org_created
          ON document_templates (organization_id, created_at DESC)
          WHERE deleted_at IS NULL;
        """
    )

    # RLS — symmetric policy, identical GUC expression. FORCE so the
    # owner role (crm_app runs NOBYPASSRLS) cannot sidestep it.
    op.execute("ALTER TABLE document_templates ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE document_templates FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON document_templates
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON document_templates TO crm_app;")

    # Provenance FK on contracts — which template seeded the body.
    op.add_column("contracts", sa.Column("applied_template_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_contracts_applied_template_id",
        "contracts",
        "document_templates",
        ["applied_template_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint("fk_contracts_applied_template_id", "contracts", type_="foreignkey")
    op.drop_column("contracts", "applied_template_id")

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON document_templates;")
    op.execute("ALTER TABLE document_templates NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE document_templates DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP INDEX IF EXISTS idx_document_templates_org_created;")
    op.execute("DROP INDEX IF EXISTS uq_document_templates_org_name;")
    op.drop_index(op.f("ix_document_templates_deleted_at"), table_name="document_templates")
    op.drop_index(
        op.f("ix_document_templates_organization_id"), table_name="document_templates"
    )
    op.drop_table("document_templates")

    sa.Enum(name="documenttype").drop(op.get_bind(), checkfirst=True)
