"""web_forms (Web-to-Lead public capture forms)

Hand-written (NOT autogenerated): autogen mis-handles partial indexes on
the other tenant tables and would emit phantom drops. See project memory.

Adds:
  * `web_forms` — an org-scoped public capture form. `token` is the public
    `crmf_…` identifier embedded in the customer's site (plaintext, unique).
    Hard-deletable (no soft-delete); an `active` flag pauses capture.

RLS ENABLE + FORCE with the same GUC-reading policy as every other tenant
table, GRANTed to crm_app — so both the admin CRUD and the public submit
(which sets the GUC from the token's embedded org) run under tenant
isolation.

Revision ID: f2a3b4c5d6e7
Revises: e1f2a3b4c5d6
Create Date: 2026-06-07 16:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f2a3b4c5d6e7"
down_revision: Union[str, None] = "e1f2a3b4c5d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"


def upgrade() -> None:
    op.create_table(
        "web_forms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("token", sa.String(length=120), nullable=False),
        sa.Column("default_source", sa.String(length=120), nullable=True),
        sa.Column("redirect_url", sa.String(length=500), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "submission_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_web_forms_organization_id"), "web_forms", ["organization_id"])
    # Public token → form, one indexed seek. Globally unique so the public
    # path resolves a presented token without already knowing the org.
    op.create_index(op.f("ix_web_forms_token"), "web_forms", ["token"], unique=True)

    op.execute("ALTER TABLE web_forms ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE web_forms FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON web_forms
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON web_forms TO crm_app;")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON web_forms;")
    op.execute("ALTER TABLE web_forms NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE web_forms DISABLE ROW LEVEL SECURITY;")
    op.drop_index(op.f("ix_web_forms_token"), table_name="web_forms")
    op.drop_index(op.f("ix_web_forms_organization_id"), table_name="web_forms")
    op.drop_table("web_forms")
