"""tags + entity_tags (polymorphic) + saved_segments

Hand-written (NOT autogenerated): autogen produces phantom drop_index
calls for the partial indexes below. See the project memory + the
custom_fields/companies migrations' rationale.

Adds:
  * `tags` — flat, org-scoped label (name + hex colour). One live tag per
    (org, lower(name)) via a partial unique index.
  * `entity_tags` — polymorphic join attaching a tag to one entity
    (lead/customer/deal/company). Hard-deleted on untag. Unique
    (tag_id, entity_type, entity_id); lookup indexes both directions.
  * `saved_segments` — named stored filter (JSON) per entity type.

All three are RLS ENABLE + FORCE with the same GUC-reading policy as
every other tenant table, and GRANTed to crm_app.

Revision ID: e1f2a3b4c5d6
Revises: d0e1f2a3b4c5
Create Date: 2026-06-07 14:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "e1f2a3b4c5d6"
down_revision: Union[str, None] = "d0e1f2a3b4c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Byte-identical to the other tenant tables so GUC semantics match.
GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"

_RLS_TABLES = ("tags", "entity_tags", "saved_segments")


def _enable_rls(table: str) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON {table}
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO crm_app;")


def upgrade() -> None:
    # --- tags ---------------------------------------------------------
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("color", sa.String(length=7), server_default="#64748b", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_organization_id"), "tags", ["organization_id"])
    op.create_index(op.f("ix_tags_deleted_at"), "tags", ["deleted_at"])
    # One live tag per (org, name), case-insensitive. Partial on deleted_at
    # so re-adding a deleted tag's name doesn't collide.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_tag_org_name
          ON tags (organization_id, lower(name))
          WHERE deleted_at IS NULL;
        """
    )

    # --- entity_tags --------------------------------------------------
    op.create_table(
        "entity_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entity_tags_organization_id"), "entity_tags", ["organization_id"])
    op.create_index(op.f("ix_entity_tags_tag_id"), "entity_tags", ["tag_id"])
    # One attachment per (tag, entity) — idempotent assign.
    op.create_unique_constraint(
        "uq_entity_tag", "entity_tags", ["tag_id", "entity_type", "entity_id"]
    )
    # "Tags for this entity" — the chip-rendering query path.
    op.create_index(
        "idx_entity_tags_lookup",
        "entity_tags",
        ["organization_id", "entity_type", "entity_id"],
    )

    # --- saved_segments ----------------------------------------------
    op.create_table(
        "saved_segments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_segments_organization_id"), "saved_segments", ["organization_id"]
    )
    op.create_index(op.f("ix_saved_segments_deleted_at"), "saved_segments", ["deleted_at"])
    op.execute(
        """
        CREATE INDEX idx_saved_segments_org_entity
          ON saved_segments (organization_id, entity_type)
          WHERE deleted_at IS NULL;
        """
    )

    for tbl in _RLS_TABLES:
        _enable_rls(tbl)


def downgrade() -> None:
    for tbl in _RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {tbl};")
        op.execute(f"ALTER TABLE {tbl} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {tbl} DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP INDEX IF EXISTS idx_saved_segments_org_entity;")
    op.drop_index(op.f("ix_saved_segments_deleted_at"), table_name="saved_segments")
    op.drop_index(op.f("ix_saved_segments_organization_id"), table_name="saved_segments")
    op.drop_table("saved_segments")

    op.drop_index("idx_entity_tags_lookup", table_name="entity_tags")
    op.drop_constraint("uq_entity_tag", "entity_tags", type_="unique")
    op.drop_index(op.f("ix_entity_tags_tag_id"), table_name="entity_tags")
    op.drop_index(op.f("ix_entity_tags_organization_id"), table_name="entity_tags")
    op.drop_table("entity_tags")

    op.execute("DROP INDEX IF EXISTS uq_tag_org_name;")
    op.drop_index(op.f("ix_tags_deleted_at"), table_name="tags")
    op.drop_index(op.f("ix_tags_organization_id"), table_name="tags")
    op.drop_table("tags")
