"""automation_rules + automation_runs (no-/low-code automation, ADR-007)

Hand-written (NOT autogenerated): autogen mis-handles the partial / DESC
indexes on the existing tenant tables and would emit phantom drops. See
project memory.

Adds:
  * `automation_rules` — an org-scoped "when <trigger>, do <action>" rule.
    `action_config` is a JSON text blob whose shape depends on the action.
    Org-scoped, RLS ENABLE + FORCE with the standard GUC policy, GRANTed to
    crm_app. Config object → hard-deletable.
  * `automation_runs` — the execution log + idempotency ledger. NOT RLS'd
    (the worker writes cross-org, same as outbox_events / webhook_deliveries);
    `idempotency_key` is UNIQUE so a retried event or a same-day stale scan
    can't double-fire. GRANTed to crm_app.

Revision ID: b4c5d6e7f8a9
Revises: a3b4c5d6e7f8
Create Date: 2026-06-08 09:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b4c5d6e7f8a9"
down_revision: Union[str, None] = "a3b4c5d6e7f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


GUC_EXPR = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"

_TRIGGER = sa.Enum(
    "lead_created",
    "deal_created",
    "deal_won",
    "deal_lost",
    "deal_stage_changed",
    "lead_stale",
    name="automationtrigger",
)
_ACTION = sa.Enum(
    "create_task",
    "send_notification",
    "change_stage",
    name="automationaction",
)


def upgrade() -> None:
    op.create_table(
        "automation_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("trigger", _TRIGGER, nullable=False),
        sa.Column("action", _ACTION, nullable=False),
        sa.Column("action_config", sa.Text(), nullable=False, server_default="{}"),
        sa.Column("run_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_automation_rules_organization_id"), "automation_rules", ["organization_id"]
    )

    op.create_table(
        "automation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["automation_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_automation_runs_idempotency_key"),
    )
    op.create_index(op.f("ix_automation_runs_rule_id"), "automation_runs", ["rule_id"])
    op.create_index(
        op.f("ix_automation_runs_organization_id"), "automation_runs", ["organization_id"]
    )

    # automation_rules is a tenant table: RLS ENABLE + FORCE + standard policy.
    op.execute("ALTER TABLE automation_rules ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE automation_rules FORCE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON automation_rules
          FOR ALL
          USING (organization_id = {GUC_EXPR})
          WITH CHECK (organization_id = {GUC_EXPR});
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON automation_rules TO crm_app;")
    # automation_runs is the worker's cross-org ledger (not RLS'd, like
    # outbox_events / webhook_deliveries) — just grant table privileges.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON automation_runs TO crm_app;")


def downgrade() -> None:
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON automation_runs TO crm_app;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON automation_rules;")
    op.execute("ALTER TABLE automation_rules NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE automation_rules DISABLE ROW LEVEL SECURITY;")
    op.drop_index(op.f("ix_automation_runs_organization_id"), table_name="automation_runs")
    op.drop_index(op.f("ix_automation_runs_rule_id"), table_name="automation_runs")
    op.drop_table("automation_runs")
    op.drop_index(op.f("ix_automation_rules_organization_id"), table_name="automation_rules")
    op.drop_table("automation_rules")
    op.execute("DROP TYPE IF EXISTS automationaction;")
    op.execute("DROP TYPE IF EXISTS automationtrigger;")
