"""task_customer_version_optimistic_locking

Revision ID: 9a8b7c6d5e4f
Revises: f6a7b8c9d0e1
Create Date: 2026-06-04 12:30:00.000000+00:00

TD-12 follow-up (§321). Extend the Deal optimistic-locking pattern to
`customers` and `tasks`: add `version int NOT NULL DEFAULT 0` so their
update endpoints can compare-and-set against an `If-Match` header.
Mirrors migration `4d3d59906702` (deals). Header stays optional in v1
(a missing header logs a warning) so the frontend can roll out without
landing in lockstep.

Hand-written (NOT autogenerated) — autogen emits phantom drop_index
calls for our partial / DESC indices.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "9a8b7c6d5e4f"
down_revision: Union[str, None] = "f6a7b8c9d0e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    for table in ("customers", "tasks"):
        op.add_column(
            table,
            sa.Column("version", sa.Integer(), nullable=False, server_default="0"),
        )


def downgrade() -> None:
    for table in ("customers", "tasks"):
        op.drop_column(table, "version")
