import enum
import uuid
from datetime import date, datetime

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class UserRole(str, enum.Enum):
    admin = "admin"
    manager = "manager"
    sales_agent = "sales_agent"
    support_agent = "support_agent"
    client = "client"


class LeadStage(str, enum.Enum):
    new = "new"
    contacted = "contacted"
    qualified = "qualified"
    proposal_sent = "proposal_sent"
    negotiation = "negotiation"
    won = "won"
    lost = "lost"


class DealStage(str, enum.Enum):
    new = "new"
    qualified = "qualified"
    proposal_sent = "proposal_sent"
    negotiation = "negotiation"
    won = "won"
    lost = "lost"


class Currency(str, enum.Enum):
    EUR = "EUR"
    CHF = "CHF"
    USD = "USD"
    GBP = "GBP"


class TaskStatus(str, enum.Enum):
    todo = "todo"
    in_progress = "in_progress"
    done = "done"


class TaskPriority(str, enum.Enum):
    low = "low"
    medium = "medium"
    high = "high"


class Plan(str, enum.Enum):
    free = "free"
    standard = "standard"
    premium = "premium"


class BillingCycle(str, enum.Enum):
    monthly = "monthly"
    yearly = "yearly"


# SoftDeleteMixin moved to `app.mixins` to break a circular import
# (database.py needs the mixin class to wire its global filter event;
# models.py needs Base from database.py). Re-exported here so any
# existing `from app.models import SoftDeleteMixin` keeps working.
from app.mixins import SoftDeleteMixin  # noqa: E402


class Organization(Base):
    """A tenant. Owns billing, subscriptions, and every domain entity
    (leads, customers, deals, tasks). Created on first sign-up and via
    the invite/onboarding flows. Stripe sees one Customer per Organization
    — seats are users within the org, not separate Stripe customers.
    """

    __tablename__ = "organizations"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    # URL-friendly identifier — used in future org-scoped routes and as
    # a stable handle in logs. Unique across the install.
    slug: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)

    # Billing — these will MOVE here from User once every endpoint that
    # reads user.plan is refactored. For now both Organization and User
    # carry the columns; the org is the source of truth for new code.
    plan: Mapped[Plan] = mapped_column(
        Enum(Plan), default=Plan.free, server_default=Plan.free.value, nullable=False
    )
    billing_cycle: Mapped[BillingCycle] = mapped_column(
        Enum(BillingCycle),
        default=BillingCycle.monthly,
        server_default=BillingCycle.monthly.value,
        nullable=False,
    )
    plan_started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    plan_renewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    plan_canceled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    trial_ends_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    stripe_customer_id: Mapped[str | None] = mapped_column(String(255), index=True)
    stripe_subscription_id: Mapped[str | None] = mapped_column(String(255), index=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    memberships: Mapped[list["OrgMembership"]] = relationship(
        back_populates="organization", cascade="all, delete-orphan"
    )


class OrgInvite(Base):
    """A pending invitation for an email to join an Organization.

    Generated by an org admin, carries the role the invitee will get on
    accept. The `token` is the URL-safe handle delivered out-of-band
    (email today is just a stdout log; real SMTP comes in P1 auth
    hardening). `accepted_at` is the single-use marker — once set the
    token is dead. `expires_at` defaults to +7 days at insert time.
    """

    __tablename__ = "org_invites"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    email: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    role: Mapped[UserRole] = mapped_column(Enum(UserRole), nullable=False)
    # URL-safe token, ~43 chars from secrets.token_urlsafe(32). Unique
    # globally so an exposed token can be looked up directly without
    # needing the org slug in the URL.
    token: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    accepted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    organization: Mapped[Organization] = relationship()


class PasswordResetToken(Base):
    """Single-use, time-bounded credential for the forgot-password flow.

    The token (URL-safe, ~43 chars from `secrets.token_urlsafe(32)`) is
    delivered to the user out-of-band — today via the dev log line
    `password_reset.dispatched url=…`, eventually via SMTP. Possession
    of a valid (not-expired, not-used) token authorises one password
    change for the bound user.

    Burning: `used_at` is set on successful reset; any further attempt
    with the same token returns 410 Gone.
    """

    __tablename__ = "password_reset_tokens"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    token: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class MfaBackupCode(Base):
    """Single-use one-time recovery code for the TOTP MFA flow.

    Ten codes are generated when MFA is enabled. They cover the
    "authenticator app is lost / phone died" path: a user submits a
    code to /mfa/verify instead of a TOTP, and it's burned on use.
    The plaintext code is shown to the user ONCE at enable time and
    never persisted — we store only a bcrypt hash, same model as
    passwords. Listing codes after enable returns just the count of
    remaining (unused) codes, never the codes themselves.
    """

    __tablename__ = "mfa_backup_codes"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    code_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class OrgMembership(Base):
    """Many-to-many junction between User and Organization. Each row holds
    the user's role inside that org — so the same user can be admin in
    one org and sales_agent in another. The composite PK guarantees one
    membership row per (user, org) pair.
    """

    __tablename__ = "org_memberships"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), primary_key=True
    )
    role: Mapped[UserRole] = mapped_column(Enum(UserRole), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    user: Mapped["User"] = relationship(back_populates="memberships")
    organization: Mapped[Organization] = relationship(back_populates="memberships")


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True, nullable=False)
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    # `role` is the LEGACY single-tenant role — kept while we migrate every
    # callsite to OrgMembership.role. Will be dropped in a follow-up.
    role: Mapped[UserRole] = mapped_column(
        Enum(UserRole), default=UserRole.sales_agent, nullable=False
    )
    locale: Mapped[str] = mapped_column(String(5), default="en", nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    # TOTP MFA. `mfa_secret` is the base32 shared secret bound to the
    # user's authenticator app — plaintext in v1 (env-level encryption
    # is a follow-up; today the DB itself is the trust boundary).
    # Populated when /setup runs; only honoured when `mfa_enabled` is
    # True. `mfa_enrolled_at` records the moment the user finished
    # /enable so audit traces have a timestamp.
    mfa_enabled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    mfa_secret: Mapped[str | None] = mapped_column(String(64))
    mfa_enrolled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Which org the user is currently working in. Set on login from the
    # first membership; the user can switch via PATCH /me. Null when the
    # user has zero memberships (shouldn't happen post-migration, but
    # SET NULL avoids a circular FK problem at cascade-delete time).
    last_active_org_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="SET NULL"),
    )

    # Billing fields used to live here in the single-tenant era; they now
    # live on `Organization` (see ADR-013). The migration that dropped
    # them is `<revision>_drop_user_billing_columns`.

    # Optional team membership. A user can belong to at most one team
    # in v1 (a many-to-many junction is a follow-up if real customers
    # need cross-team users). `SET NULL` on team delete so wiping a
    # team doesn't orphan its members.
    team_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("teams.id", ondelete="SET NULL"),
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    leads: Mapped[list["Lead"]] = relationship(back_populates="owner")
    deals: Mapped[list["Deal"]] = relationship(back_populates="owner")
    tasks: Mapped[list["Task"]] = relationship(
        back_populates="assignee", foreign_keys="Task.assignee_id"
    )
    memberships: Mapped[list[OrgMembership]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class Lead(SoftDeleteMixin, Base):
    __tablename__ = "leads"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # Tenant scope — NOT NULL after backfill. Every query MUST filter by
    # this column; RLS will enforce defense-in-depth in a later iteration.
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    first_name: Mapped[str] = mapped_column(String(120), nullable=False)
    last_name: Mapped[str] = mapped_column(String(120), nullable=False)
    email: Mapped[str | None] = mapped_column(String(255), index=True)
    phone: Mapped[str | None] = mapped_column(String(50))
    company: Mapped[str | None] = mapped_column(String(255))
    industry: Mapped[str | None] = mapped_column(String(120))
    country: Mapped[str | None] = mapped_column(String(2))
    company_size: Mapped[int | None] = mapped_column(Integer)
    budget: Mapped[float | None] = mapped_column(Float)
    source: Mapped[str | None] = mapped_column(String(120))
    notes: Mapped[str | None] = mapped_column(Text)

    stage: Mapped[LeadStage] = mapped_column(Enum(LeadStage), default=LeadStage.new, nullable=False)
    # Optional team scope — when set, the lead shows up under that
    # team's filtered list view. `SET NULL` on team delete so the
    # lead doesn't disappear when a team is wound down.
    team_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("teams.id", ondelete="SET NULL"),
        index=True,
    )

    ai_score: Mapped[int | None] = mapped_column(Integer)
    ai_priority: Mapped[str | None] = mapped_column(String(20))
    ai_next_action: Mapped[str | None] = mapped_column(Text)
    ai_conversion_probability: Mapped[float | None] = mapped_column(Float)
    ai_risk_analysis: Mapped[str | None] = mapped_column(Text)
    ai_scored_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    owner_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    owner: Mapped[User | None] = relationship(back_populates="leads")

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Customer(SoftDeleteMixin, Base):
    __tablename__ = "customers"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    first_name: Mapped[str] = mapped_column(String(120), nullable=False)
    last_name: Mapped[str] = mapped_column(String(120), nullable=False)
    email: Mapped[str | None] = mapped_column(String(255), index=True)
    phone: Mapped[str | None] = mapped_column(String(50))
    company: Mapped[str | None] = mapped_column(String(255))
    industry: Mapped[str | None] = mapped_column(String(120))
    country: Mapped[str | None] = mapped_column(String(2))
    address: Mapped[str | None] = mapped_column(Text)
    website: Mapped[str | None] = mapped_column(String(255))
    notes: Mapped[str | None] = mapped_column(Text)

    ai_summary: Mapped[str | None] = mapped_column(Text)
    ai_summary_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    owner_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    deals: Mapped[list["Deal"]] = relationship(back_populates="customer")

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Deal(SoftDeleteMixin, Base):
    __tablename__ = "deals"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    value: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    currency: Mapped[Currency] = mapped_column(Enum(Currency), default=Currency.EUR, nullable=False)
    stage: Mapped[DealStage] = mapped_column(Enum(DealStage), default=DealStage.new, nullable=False)
    probability: Mapped[int] = mapped_column(Integer, default=10, nullable=False)
    expected_close_date: Mapped[date | None] = mapped_column(Date)
    notes: Mapped[str | None] = mapped_column(Text)
    # Optional team scope (see Lead.team_id for the rationale).
    team_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("teams.id", ondelete="SET NULL"),
        index=True,
    )

    # Soft ordering inside a stage column for kanban drag-drop.
    sort_index: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Optimistic locking — bumped on every mutation. Clients send the
    # current value as `If-Match: <version>` on PATCH/move; mismatch
    # returns 409. Mitigates the silent-overwrite class of bugs when
    # two sales reps edit the same deal during a meeting. v1 ships
    # with the header OPTIONAL (logs a warning if missing) so a
    # frontend rollout doesn't have to land in lockstep.
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    customer_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("customers.id", ondelete="SET NULL")
    )
    customer: Mapped[Customer | None] = relationship(back_populates="deals")

    owner_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    owner: Mapped[User | None] = relationship(back_populates="deals")

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Task(SoftDeleteMixin, Base):
    __tablename__ = "tasks"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    status: Mapped[TaskStatus] = mapped_column(
        Enum(TaskStatus), default=TaskStatus.todo, nullable=False
    )
    priority: Mapped[TaskPriority] = mapped_column(
        Enum(TaskPriority), default=TaskPriority.medium, nullable=False
    )
    due_date: Mapped[date | None] = mapped_column(Date)

    assignee_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    assignee: Mapped[User | None] = relationship(back_populates="tasks", foreign_keys=[assignee_id])

    customer_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("customers.id", ondelete="SET NULL")
    )
    deal_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("deals.id", ondelete="SET NULL"))
    lead_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("leads.id", ondelete="SET NULL"))

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Notification(Base):
    """In-app notification for a single user.

    Distinct from `Activity` (entity timeline, visible to anyone in
    the org) and `AuditLog` (admin compliance ledger): a notification
    is something one specific person is supposed to ACT on — a task
    they were just assigned, a deal that moved in their pipeline.
    Renders in the header bell + unread counter.

    `type` is a curated slug (see `app.notifications.NotificationType`)
    so the UI can map to an icon + i18n label without parsing
    free-form text. `link_url` is the in-app target the bell links
    to ("go to the task that was just assigned"). `read_at` is null
    until the user opens / dismisses the entry.

    Not soft-deletable — notifications are an ephemeral inbox, not
    a record. A future retention cron prunes anything > 90 days
    (P3 follow-up).
    """

    __tablename__ = "notifications"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Optional actor — the user whose action triggered this
    # notification. Lets the UI render "Alice assigned you a task"
    # instead of an anonymous "task assigned".
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    type: Mapped[str] = mapped_column(String(60), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str | None] = mapped_column(Text)
    # Relative path (e.g. `/leads/<uuid>`) the bell can link to. Not
    # absolute so locale prefix is added client-side.
    link_url: Mapped[str | None] = mapped_column(String(500))
    metadata_json: Mapped[str | None] = mapped_column(Text)
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class PipelineKind(str, enum.Enum):
    """A pipeline is either a LEAD pipeline (qualification funnel) or a
    DEAL pipeline (sales funnel). They have different semantics + render
    in different views; keeping them as separate kinds lets one org
    have multiple of each (Inbound vs Outbound leads, Enterprise vs
    SMB deals)."""

    lead = "lead"
    deal = "deal"


class Pipeline(SoftDeleteMixin, Base):
    """Customer-defined funnel. Replaces the hardcoded LeadStage /
    DealStage enums (which are kept as a denormalised cache during
    the multi-phase migration — see ADR / skills.md).

    `is_default` exists so each org has exactly one default pipeline
    per kind — that's where `Lead.create` lands by default, where the
    kanban opens on first visit, etc. Enforced application-side
    (one-of-N within the same kind via the endpoint that toggles it);
    the DB-level guarantee would need a partial unique index that
    Phase 2 will add once we trust the data shape.
    """

    __tablename__ = "pipelines"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    kind: Mapped[PipelineKind] = mapped_column(Enum(PipelineKind), nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    slug: Mapped[str] = mapped_column(String(120), nullable=False)
    is_default: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    stages: Mapped[list["PipelineStage"]] = relationship(
        back_populates="pipeline",
        cascade="all, delete-orphan",
        order_by="PipelineStage.position",
    )


class PipelineStage(SoftDeleteMixin, Base):
    """One column on a Pipeline's kanban. `position` is the sort
    order (small int = leftmost). `probability` is the % chance a
    deal at this stage closes won — used by the forecast widget.

    `is_won` / `is_lost` flag the terminal stages: when a deal lands
    in an `is_won` stage we treat it as realised revenue; in
    `is_lost` we treat it as discarded. Multiple won/lost stages
    per pipeline are allowed (some teams want "Won — direct" vs
    "Won — referral" for attribution).
    """

    __tablename__ = "pipeline_stages"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    pipeline_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("pipelines.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    slug: Mapped[str] = mapped_column(String(120), nullable=False)
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    probability: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    is_won: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_lost: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    pipeline: Mapped[Pipeline] = relationship(back_populates="stages")


class Team(SoftDeleteMixin, Base):
    """A group of users inside an Organization — e.g. "Inbound EU",
    "Enterprise NA", "Renewals". Optional grouping (orgs work fine
    without any teams); when set, enables team-scoped list filters
    on Lead/Deal and the future round-robin assignment helper.

    Per-org slug unique (partial unique index in migration so soft-
    deleted teams free the slug). Soft-deletable so re-creating a
    team with the same name doesn't lose the historical reference
    from leads/deals that pointed at it (`team_id` on those rows
    is `SET NULL` on hard-delete via the FK; soft-delete keeps the
    relationship visible in audit-style reads).
    """

    __tablename__ = "teams"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    # URL-safe slug for future /teams/{slug} routing; unique per org
    # via the partial index in the migration (NOT a column UNIQUE
    # because we want soft-deleted rows to free the slug).
    slug: Mapped[str] = mapped_column(String(120), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class FileAttachment(SoftDeleteMixin, Base):
    """File attached to a Lead / Customer / Deal — uploaded contract,
    deck, scanned form, etc. The blob lives in S3 (or any S3-compatible
    store; MinIO in dev); this row is the metadata index.

    Polymorphic by `(entity_type, entity_id)` like Activity and Note.
    Soft-delete on the row; the S3 object is HARD-deleted on user
    delete to free storage immediately (restoring a soft-deleted
    attachment would require re-uploading the file — accepted
    trade-off vs. paying for orphaned blob storage indefinitely).

    Hashing: `sha256` lets us detect duplicates (same file uploaded
    twice → same hash) and verify integrity on download. Optional
    in v1 (computed at upload time; never re-verified yet).
    """

    __tablename__ = "file_attachments"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # `uploader_user_id` SET NULL on user delete — the audit trail
    # is the source of truth for "who did what"; the attachment
    # itself stays attached to the entity even if the uploader leaves.
    uploader_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    entity_type: Mapped[str] = mapped_column(String(40), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    # Original filename as the user uploaded it — preserved verbatim
    # so the download Content-Disposition can re-use it.
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    content_type: Mapped[str] = mapped_column(String(120), nullable=False)
    size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    # S3 object key — see `app.storage.object_key` for the layout.
    storage_key: Mapped[str] = mapped_column(String(500), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Note(SoftDeleteMixin, Base):
    """Free-form markdown note attached to a Lead / Customer / Deal.

    Distinct from the `notes` text field on Lead/Customer — that was
    a single shared scratchpad; this is a per-user, multi-entry log
    where every team member can drop observations. Renders in the
    detail page's NotesPanel; creating one also emits a
    `note_added` Activity so the timeline reflects it.

    Polymorphic by (entity_type, entity_id) so a future Quote /
    Contract / Project can take notes too without a schema change.
    Soft-deletable (inherits `SoftDeleteMixin`) so the trash bin
    covers them like every other tenant entity.
    """

    __tablename__ = "notes"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # `author_user_id` is the user who wrote the note. Nullable in
    # principle (CASCADE SET NULL on user delete) but we never insert
    # NULL — the endpoint always sets it from `get_current_user`.
    author_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    entity_type: Mapped[str] = mapped_column(String(40), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    # Markdown source — rendering is the frontend's job. Length cap
    # is generous; CRM notes occasionally include longer meeting
    # transcripts. 16kB matches what most modern textareas handle
    # before they start visibly lagging.
    body: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Activity(Base):
    """User-facing event timeline: "what happened to THIS lead /
    customer / deal, in human terms".

    Distinct from `AuditLog`:
      * `AuditLog` is the SECURITY ledger (compliance, forensics,
        admin-only). It records every mutation including system
        events with no user-friendly mapping.
      * `Activity` is the USER-FACING ledger rendered on the entity
        detail page. Curated: only the events a sales rep cares
        about (created, stage_change, score, note_added, …) and
        always tagged with a user-friendly `type` from the enum
        below.

    Polymorphic by `entity_type + entity_id` (Lead | Customer | Deal)
    so a future Quote / Contract entity can join the timeline
    without a schema change. Append-only — never updated, never
    soft-deleted; if the underlying entity is purged, CASCADE on
    the lead/customer/deal FKs handles cleanup via the indirect
    path (we store entity_id as plain UUID, no DB-level FK because
    polymorphic, so we rely on the `purge_orphans` follow-up).
    """

    __tablename__ = "activities"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # `actor_user_id` is nullable: system-emitted activities (an
    # incoming-email auto-import, a scheduled re-score) have no user.
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    entity_type: Mapped[str] = mapped_column(String(40), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    # Free-form type slug — the enum lives in the API layer
    # (`app.activities.ActivityType`) so adding a new type doesn't
    # need a DB migration. UI maps the slug → translated label.
    type: Mapped[str] = mapped_column(String(40), nullable=False)
    # Optional human-readable summary ("Stage moved from new →
    # qualified"). Localised on render — see frontend.
    content: Mapped[str | None] = mapped_column(Text)
    # Structured payload for type-specific fields (old/new stage,
    # AI score number, etc). JSON serialised to keep schema flexible.
    metadata_json: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class AuditLog(Base):
    __tablename__ = "audit_logs"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # Nullable: platform-level events (a user logging in before they've
    # picked an org, webhook idempotency reconciliation) have no org
    # context. Tenant-scoped audits MUST set this.
    organization_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="SET NULL"),
        index=True,
    )
    actor_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    action: Mapped[str] = mapped_column(String(120), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(80), nullable=False)
    entity_id: Mapped[str | None] = mapped_column(String(80))
    metadata_json: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class StripeEvent(Base):
    """Idempotency log for Stripe webhook events.

    Stripe re-delivers events on retry. We must dedupe by event id to avoid
    crediting a subscription twice or rolling back a cancellation.
    """

    __tablename__ = "stripe_events"

    id: Mapped[str] = mapped_column(String(255), primary_key=True)  # Stripe event id
    type: Mapped[str] = mapped_column(String(120), nullable=False, index=True)
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    payload: Mapped[str] = mapped_column(Text, nullable=False)


class WebhookEndpoint(Base):
    """One subscriber's HTTP receiver for outbox events. Per-org.

    Each endpoint subscribes to a (curated) list of `EventType` slugs
    via `enabled_events` (or the wildcard `["*"]` meaning "every
    event"). The outbox dispatcher's webhook handler looks up the
    matching endpoints for an event's org + event_type, then enqueues
    one `deliver_webhook` arq job per (endpoint, event) pair. Per-
    delivery retry is then arq's job, isolated from the outbox drain
    so a slow receiver can't back-pressure the foundation.

    `secret` is hex 64 (32 bytes random), shown ONCE on create and
    never round-tripped on subsequent reads (mirrors how Stripe /
    GitHub render webhook signing secrets). Used by `app.webhook_sign`
    to compute the `X-CRM-Signature: t=<ts>,v1=<hex>` header.

    `consecutive_failures` auto-increments per failed delivery and
    resets on success. When it crosses `WEBHOOK_AUTO_PAUSE_THRESHOLD`
    (10), `paused_at` is set automatically — admin has to manually
    unpause via PATCH so a broken endpoint doesn't keep burning
    retries forever. `last_success_at` / `last_failure_at` surface
    in the admin UI for triage.

    Not soft-deletable: deleting an endpoint is a permanent op the
    admin chose intentionally. The CASCADE on org delete keeps things
    tidy when a tenant goes away.
    """

    __tablename__ = "webhook_endpoints"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    url: Mapped[str] = mapped_column(String(2048), nullable=False)
    secret: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str | None] = mapped_column(String(255))
    # JSON-encoded array of event_type strings. `["*"]` = subscribe
    # to every event. Kept as text not Postgres ARRAY so the schema
    # stays portable (sqlite for unit tests, etc).
    enabled_events: Mapped[str] = mapped_column(Text, nullable=False, default='["*"]')
    paused_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    consecutive_failures: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_success_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_failure_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class WebhookDelivery(Base):
    """One attempt to deliver one event to one endpoint.

    Cardinality: N (events) x M (matching endpoints) x P (retries).
    Useful for: "did my webhook fire for that lead?" triage in the
    admin UI, audit of what we tried to send, p95 latency tracking
    of receivers.

    `response_body_excerpt` is capped at 2 KB — the receiver's body
    might be huge (HTML error pages) and we don't want to balloon
    the DB. `latency_ms` is the wall time of the HTTP round trip,
    NOT including retry waits.

    Not RLS'd (same reasoning as outbox_events — the worker drains
    cross-org); admin endpoint filters by `organization_id` of the
    parent WebhookEndpoint via JOIN.
    """

    __tablename__ = "webhook_deliveries"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    endpoint_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("webhook_endpoints.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Soft pointer (no FK): outbox rows can be pruned before their
    # deliveries; we still want the delivery row to survive for
    # historical triage.
    event_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    event_type: Mapped[str] = mapped_column(String(80), nullable=False)
    attempt: Mapped[int] = mapped_column(Integer, nullable=False)
    # "pending" while the arq job is queued, "success" / "failed" once it ran.
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    response_code: Mapped[int | None] = mapped_column(Integer)
    response_body_excerpt: Mapped[str | None] = mapped_column(Text)
    error: Mapped[str | None] = mapped_column(Text)
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    scheduled_for: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class OutboxEvent(Base):
    """Transactional outbox (ADR-007). Domain mutations append a row
    here in the same DB transaction as the mutation. A periodic
    worker job (`drain_outbox`) claims unprocessed rows with
    `FOR UPDATE SKIP LOCKED`, invokes the in-process subscriber
    registry, and marks them processed. Guarantees at-least-once
    delivery without distributed-transaction pain.

    Not RLS'd on purpose: the worker (`crm_app` role,
    NOSUPERUSER/NOBYPASSRLS) needs to drain across all tenants in
    one pass; admin-facing reads filter by `organization_id`
    explicitly in the endpoint. `organization_id` is nullable so
    platform-level events (auth, billing webhook fan-out) can use
    the same channel.
    """

    __tablename__ = "outbox_events"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=True,
    )
    event_type: Mapped[str] = mapped_column(String(80), nullable=False)
    payload: Mapped[str | None] = mapped_column(Text)
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_error: Mapped[str | None] = mapped_column(Text)
